language: python
python:
  - 3.4
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels yasserglez
  - conda config --add channels ioos
  - conda update -q conda
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION pip
  - source activate test-env
  - pip install -r tests/requirements.txt
install:
  - conda install -n test-env "numpy >= 1.9.1"
  - conda install -n test-env "scipy >= 0.14.0"
  - conda install -n test-env "python-igraph >= 0.7.1"
  - conda install -n test-env "beautifulsoup4 >= 4.3.2"
  - conda install -n test-env "fann2"
  - conda install -n test-env "fim"
  - pip install https://github.com/remiomosowon/pyeasyga/zipball/master
  - pip install https://github.com/sawcordwell/pymdptoolbox/zipball/master
  - pip install https://github.com/pybrain/pybrain/zipball/master
  - pip install -e .
script:
  - py.test --verbose
