package:
  name: fann2
  version: "1.0.0"

source:
  git_url: https://github.com/FutureLinkCorporation/fann2

build:
  number: 0

requirements:
  build:
    - fann ==2.2.0
    - swig
    - python
    - setuptools
  run:
    - fann ==2.2.0
    - python

about:
  home: https://github.com/FutureLinkCorporation/fann2
  summary: Python Bindings for the Fast Artificial Neural Network Library
  license: LGPL-2.1
