package:
  name: python-igraph
  version: "0.7.1.post6"

source:
  fn: python-igraph-0.7.1-4.tar.gz
  url: https://pypi.python.org/packages/source/p/python-igraph/python-igraph-0.7.1.post6.tar.gz
  md5: a4c0b5960735b36adb5d3a40031cb7c0

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - igraph ==0.7.1
    - setuptools
    - python
  run:
    - igraph ==0.7.1
    - python

about:
  home: http://igraph.org/
  summary: High performance graph data structures and algorithms
  license: GPL-2
