package:
  name: fim
  version: "6.12"

source:
  fn: pyfim.tar.gz
  url: http://www.borgelt.net/src/pyfim.tar.gz
  md5: 84a540cc868a5d0c451e8de503d55122

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

about:
  home: http://www.borgelt.net/pyfim.html
  summary: Frequent Item Set Mining and Association Rule Induction for Python
  license: MIT
